#!/bin/bash
t=$(echo -e "$1" | xargs)
[[ "$t" ]] || t="$(cat -)"
TEXT=$(node -p "encodeURIComponent('$t')")
curl "https://tts.voicetech.yandex.net/generate?text=$TEXT&speed=1.1&format=mp3&lang=ru-RU&speaker=ermil&key=57f9c9a5-cb14-46df-b0c6-72af7fadf6b3&emotion=good" 2>/dev/null |\
	(
		has=$(has-music)
		[[ "$has" ]] && (pause-music;sleep 1)
		v=$(get-vol)
		echo $v
		[ "$(date +%H)" -ge 9 ] && vol 400
		echo $(get-vol)
		mpg321 -q -
		vol $v
		[[ "$has" ]] && (sleep 1;resume-music)
	) || :
